"use client"

import type React from "react"
import { createContext, useContext, useState } from "react"
import { ASSOCIATION_CONFIG } from "@/config/associations"

export type Language = "en" | "ne"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, replacements?: Record<string, string | number>) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  const t = (key: string, replacements?: Record<string, string | number>): string => {
    const keys = key.split(".")
    let value: any = translations[language]

    for (const k of keys) {
      value = value?.[k]
    }

    if (!value) return key

    // Apply replacements
    if (replacements) {
      let result = value
      for (const [placeholder, replacement] of Object.entries(replacements)) {
        result = result.replace(new RegExp(`{{${placeholder}}}`, 'g'), String(replacement))
      }
      return result
    }

    return value
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}

const translations = {
  en: {
    nav: {
      home: "Home",
      about: "About",
      hotels: "Hotels",
      memberHotels: "Member Hotels",
      destinations: "Destinations",
      events: "Events",
      gallery: "Gallery",
      members: "Members",
      contact: "Contact",
      login: "Login",
      memberPortal: "Member Portal",
      admin: "Admin",
      logout: "Logout",
      resources: " Resources",
      blogs: "Blogs",
      news: "News",
      downloads: "Downloads",
      careers: "Careers",
    },
    home: {
      hero: {
        title: "Unity Hotel and Guesthouse Business Association of Nepal",
        subtitle: "Unity Hotel and Guesthouse Business Association of Nepal is a dedicated organization representing the hospitality sector in Kathmandu. Established in 2074 B.S., it serves as the umbrella organization for {{count}} active hotel business associations.",
        cta: "Explore Our Members",
        exploreBtn: "Explore Hotels",
        learnMore: "Learn More",
        badge: "Discover Premium Hospitality",
        slide2Title: "{{count}} Active Hotel Associations",
        slide2Subtitle: "Operating in key areas of Kathmandu, including Kalanki, Sundhara, Bagbazar, Koteshwor, Airport, Chabahil, New Bus Park, and Balaju.",
        slide2Cta: "View Locations",
        slide3Title: "Join Our Community",
        slide3Subtitle: "Be part of Kathmandu's premier hospitality network. Connect with industry leaders and grow your business.",
        slide3Cta: "Learn More",
      },
      ticker: {
        aboutDhba: "About Us",
        aboutDesc: "Representing hospitality sector since 2074 B.S.",
        annualMeeting: "Annual General Meeting",
        meetingDesc: "Join us for networking opportunities",
        tourismGrowth: "Tourism Growth 2025",
        tourismDesc: "Latest industry insights and statistics",
        hospitalityExcellence: "Hospitality Excellence",
        excellenceDesc: "Best practices for hotel management",
        memberUnits: "Our Member Units",
        unitsDesc: "7 associations across Kathmandu",
        luxuryAccommodations: "Luxury Accommodations",
        accommodationsDesc: "Discover premium hotels in Kathmandu",
        fineDining: "Fine Dining Experience",
        diningDesc: "Explore world-class restaurants",
        wellness: "Wellness & Spa",
        wellnessDesc: "Rejuvenate at premium spa facilities",
      },
      featured: {
        title: "Explore Our Services",
        subtitle: "Discover our main services and resources to enhance your hospitality experience",
        quickAccess: "QUICK ACCESS",
        hotels: "Hotels Directory",
        destinations: "Destinations",
        events: "Events & News",
        gallery: "Photo Gallery",
      },
      committee: {
        title: "Leadership Team",
        subtitle: "Meet the dedicated leadership committed to advancing the hospitality industry",
        executive: "Executive Leadership",
        general: "General Members",
      },
      news: {
        title: "Latest News & Events",
        subtitle: "Stay informed with our latest updates",
        viewAll: "View All",
        readMore: "Read More",
      },
      newsletter: {
        title: "Subscribe to Our Newsletter",
        subtitle: "Get the latest news, events, and updates delivered to your inbox",
        placeholder: "Enter your email",
        subscribe: "Subscribe",
        success: "✓ Thank you for subscribing!",
        privacyNote: "We respect your privacy. Unsubscribe at any time.",
        confirmMessage: "Check your inbox to confirm your subscription",
        benefit1: "Latest industry news & insights",
        benefit2: "Exclusive event invitations",
        benefit3: "Member updates & announcements",
      },
    },
    about: {
      title: "About Us",
      subtitle: "Unity Hotel and Guesthouse Business Association of Nepal",
      mission: "Our Mission",
      vision: "Our Vision",
      history: "Our History",
      established: "Established in 2074 B.S.",
      description: "Unity Hotel and Guesthouse Business Association of Nepal is a dedicated organization representing the hospitality sector in Kathmandu.",
      fullDescription: "We serve as the umbrella organization for {{count}} active hotel business associations (units) operating in key areas of Kathmandu, including Kalanki, Sundhara, Bagbazar, Koteshwor, Airport, Chabahil, New Bus Park, and Balaju.",
      serviceAreas: "Our service areas include Kalanki, Sundhara, Bagbazar, Koteshwor, Airport, Chabahil, New Bus Park, and Balaju. We are committed to advocating for hotel owners' rights, upholding service standards, and collaborating with tourism authorities to enhance the industry's overall development.",
      previewTitle: "About Unity",
      previewDescription: "Unity Hotel and Guesthouse Business Association of Nepal is a dedicated organization representing the hospitality sector in Kathmandu. Established in 2074 B.S., Unity serves as the umbrella organization for {{count}} active hotel business associations.",
      readFullStory: "Read Full Story",
      leadershipTitle: "Our Leadership",
      presidentTitle: "President, Unity Kathmandu",
    },
    hotels: {
      title: "Hotels Directory",
      subtitle: "Discover premium hotels in Kathmandu",
      search: "Search hotels...",
      filter: "Filter",
      sortBy: "Sort By",
      location: "Location",
      rating: "Rating",
      priceRange: "Price Range",
      amenities: "Amenities",
      viewDetails: "View Details",
      bookNow: "Book Now",
      perNight: "per night",
      reviews: "reviews",
      noResults: "No hotels found",
    },
    destinations: {
      title: "Destinations",
      subtitle: "Explore Kathmandu's iconic landmarks",
      viewAll: "View All Destinations",
      explore: "Explore",
      description: "Description",
      location: "Location",
      openingHours: "Opening Hours",
      entryFee: "Entry Fee",
    },
    events: {
      title: "Events",
      subtitle: "Upcoming events and activities",
      upcoming: "Upcoming Events",
      past: "Past Events",
      date: "Date",
      time: "Time",
      venue: "Venue",
      register: "Register Now",
      details: "Event Details",
      noEvents: "No events scheduled",
    },
    gallery: {
      title: "Photo Gallery",
      subtitle: "Explore our collection of images",
      viewImage: "View Image",
      download: "Download",
      share: "Share",
    },
    contact: {
      title: "Contact Us",
      subtitle: "Get in touch with us",
      name: "Name",
      email: "Email",
      phone: "Phone",
      message: "Message",
      send: "Send Message",
      sending: "Sending...",
      success: "Message sent successfully!",
      error: "Failed to send message. Please try again.",
      address: "Address",
      officeHours: "Office Hours",
      followUs: "Follow Us",
    },
    auth: {
      login: "Login",
      signup: "Sign Up",
      logout: "Logout",
      email: "Email Address",
      password: "Password",
      confirmPassword: "Confirm Password",
      forgotPassword: "Forgot Password?",
      rememberMe: "Remember Me",
      noAccount: "Don't have an account?",
      haveAccount: "Already have an account?",
      resetPassword: "Reset Password",
      backToLogin: "Back to Login",
    },
    footer: {
      brand: "Unity Hotel and Guesthouse Business Association, representing premium hospitality and excellence in Nepal's capital.",
      quickLinks: "Quick Links",
      resources: "Resources",
      contact: "Contact",
      phone: "Phone",
      email: "Email",
      location: "Location",
      officeHours: "Office Hours: 9AM - 5PM (Sunday - Friday)",
      rights: "All rights reserved",
      socialLabel: "Social Links",
      privacyPolicy: "Privacy Policy",
      termsOfService: "Terms of Service",
    },
    members: {
      title: "Members",
      balaju: "Balaju Hotel Business Association",
      kalanki: "Kalanki Hotel and Guest House Association",
      kathmandu: "Kathmandu Hotel Business Association",
      nepalguesthouse: "Nepal Guest House Business Association",
      sundhara: "Sundhara Hotel Business Association",
      united: "United Hotel and Guest House",
      nepalihotel: "Nepali Hotel Business Association",
      relatedOrgs: "Related Organizations",
      membersCount: "members",
      viewProfile: "View Profile",
      contactMember: "Contact Member",
    },
    common: {
      learnMore: "Learn More",
      viewAll: "View All",
      position: "Position",
      phone: "Phone",
      contact: "Contact",
      loading: "Loading...",
      error: "Error",
      success: "Success",
      cancel: "Cancel",
      save: "Save",
      edit: "Edit",
      delete: "Delete",
      confirm: "Confirm",
      back: "Back",
      next: "Next",
      previous: "Previous",
      search: "Search",
      filter: "Filter",
      sort: "Sort",
      close: "Close",
    },
  },
  ne: {
    nav: {
      home: "होम",
      about: "बारेमा",
      hotels: "होटलहरु",
      memberHotels: "सदस्य होटलहरु",
      destinations: "गन्तव्यहरु",
      events: "कार्यक्रमहरु",
      gallery: "ग्यालेरी",
      members: "सदस्यहरु",
      contact: "संपर्क",
      login: "प्रवेश",
      memberPortal: "सदस्य पोर्टल",
      admin: "प्रशासक",
      logout: "लगआउट",
      resources: "संसाधनहरु",
      blogs: "ब्लगहरु",
      news: "समाचार",
      downloads: "डाउनलोडहरु",
      careers: "करियर",
    },
    home: {
      hero: {
        title: "एकता होटल तथा गेस्टहाउस व्यवसायी सङ्घ काठमाडौँ, नेपाल",
        subtitle: "एकता होटल तथा गेस्टहाउस व्यवसायी सङ्घ काठमाडौँको आतिथ्य क्षेत्रको प्रतिनिधित्व गर्ने एक समर्पित संस्था हो। २०७४ बि.स. मा स्थापित, यो {{count}} सक्रिय होटेल व्यवसाय संघहरूको छाता संगठनको रूपमा काम गर्दछ।",
        cta: "हाम्रा सदस्यहरू अन्वेषण गर्नुहोस्",
        exploreBtn: "होटलहरु खोज्नुहोस्",
        learnMore: "अझ जान्नुहोस्",
        badge: "प्रीमियम आतिथ्य खोज्नुहोस्",
        slide2Title: "{{count}} सक्रिय होटेल संघहरू",
        slide2Subtitle: "काठमाडौंका मुख्य क्षेत्रहरूमा सञ्चालन, कलंकी, सुन्धरा, बागबजार, कोटेश्वर, एयरपोर्ट, चाबहिल, नयाँ बसपार्क र बालाजु सहित।",
        slide2Cta: "स्थानहरू हेर्नुहोस्",
        slide3Title: "हाम्रो समुदायमा सामेल हुनुहोस्",
        slide3Subtitle: "काठमाडौंको प्रमुख आतिथ्य नेटवर्कको हिस्सा बन्नुहोस्। उद्योग नेताहरूसँग जडान गर्नुहोस् र आफ्नो व्यवसाय बढाउनुहोस्।",
        slide3Cta: "अझ जान्नुहोस्",
      },
      ticker: {
        aboutDhba: "हाम्रो बारेमा",
        aboutDesc: "२०७४ बि.स. देखि आतिथ्य क्षेत्रको प्रतिनिधित्व गर्दै",
        annualMeeting: "वार्षिक साधारण सभा",
        meetingDesc: "नेटवर्किङ अवसरहरूको लागि हामीसँग सामेल हुनुहोस्",
        tourismGrowth: "पर्यटन वृद्धि २०२५",
        tourismDesc: "नवीनतम उद्योग अन्तर्दृष्टि र तथ्याङ्क",
        hospitalityExcellence: "आतिथ्य उत्कृष्टता",
        excellenceDesc: "होटेल व्यवस्थापनका लागि उत्तम अभ्यासहरू",
        memberUnits: "हाम्रा सदस्य इकाईहरू",
        unitsDesc: "काठमाडौं भरि ७ संघहरू",
        luxuryAccommodations: "लक्जरी आवास",
        accommodationsDesc: "काठमाडौंमा प्रिमियम होटलहरू पत्ता लगाउनुहोस्",
        fineDining: "उत्कृष्ट भोजन अनुभव",
        diningDesc: "विश्व स्तरीय रेस्टुरेन्टहरू अन्वेषण गर्नुहोस्",
        wellness: "स्वास्थ्य र स्पा",
        wellnessDesc: "प्रिमियम स्पा सुविधाहरूमा पुनर्जीवित हुनुहोस्",
      },
      featured: {
        title: "हाम्रो सेवाहरु अन्वेषण गर्नुहोस्",
        subtitle: "तपाईंको आतिथ्य अनुभव बढाउन हाम्रा मुख्य सेवा र संसाधनहरु खोज्नुहोस्",
        quickAccess: "द्रुत पहुँच",
        hotels: "होटेल निर्देशिका",
        destinations: "गन्तव्यहरु",
        events: "कार्यक्रमहरु र समाचार",
        gallery: "फोटो ग्यालेरी",
      },
      committee: {
        title: "नेतृत्व दल",
        subtitle: "आतिथ्य उद्योग अग्रसर गर्न प्रतिबद्ध नेतृत्व टीमलाई भेट्नुहोस्",
        executive: "कार्यकारी नेतृत्व",
        general: "सामान्य सदस्यहरु",
      },
      news: {
        title: "ताजा समाचार र कार्यक्रमहरु",
        subtitle: "हाम्रा ताजा अपडेटहरुको साथ जानकारी रहनुहोस्",
        viewAll: "सबै देख्नुहोस्",
        readMore: "थप पढ्नुहोस्",
      },
      newsletter: {
        title: "हाम्रो न्यूजलेटर सदस्यता लिनुहोस्",
        subtitle: "ताजा समाचार, कार्यक्रम र अपडेटहरु आफ्नो इनबक्समा पाउनुहोस्",
        placeholder: "आफ्नो इमेल प्रविष्ट गर्नुहोस्",
        subscribe: "सदस्यता लिनुहोस्",
        success: "✓ सदस्यताको लागि धन्यवाद!",
        privacyNote: "हामी तपाईंको गोपनीयताको सम्मान गर्छौं। जुनसुकै बेला सदस्यता रद्द गर्नुहोस्।",
        confirmMessage: "आफ्नो सदस्यता पुष्टि गर्न आफ्नो इनबक्स जाँच गर्नुहोस्",
        benefit1: "नवीनतम उद्योग समाचार र अन्तर्दृष्टि",
        benefit2: "विशेष कार्यक्रम निमन्त्रणाहरू",
        benefit3: "सदस्य अपडेट र घोषणाहरू",
      },
    },
    about: {
      title: "हाम्रो बारेमा",
      subtitle: "एकता होटल तथा गेस्टहाउस व्यवसायी सङ्घ काठमाडौँ, नेपाल",
      mission: "हाम्रो मिशन",
      vision: "हाम्रो दृष्टिकोण",
      history: "हाम्रो इतिहास",
      established: "२०७४ बि.स. मा स्थापित",
      description: "एकता होटल तथा गेस्टहाउस व्यवसायी सङ्घ काठमाडौँको आतिथ्य क्षेत्रको प्रतिनिधित्व गर्ने एक समर्पित संस्था हो।",
      fullDescription: "हामी कलंकी, सुन्धरा, बागबजार, कोटेश्वर, एयरपोर्ट, चाबहिल, नयाँ बसपार्क र बालाजु सहित काठमाडौंका मुख्य क्षेत्रहरूमा सञ्चालन हुने {{count}} सक्रिय होटेल व्यवसाय संघहरू (इकाईहरू) को छाता संगठनको रूपमा काम गर्दछौं।",
      serviceAreas: "हाम्रो सेवा क्षेत्रहरूमा कलंकी, सुन्धरा, बागबजार, कोटेश्वर, एयरपोर्ट, चाबहिल, नयाँ बसपार्क र बालाजु समावेश छन्। हामी होटेल स्वामीहरूको अधिकारको पक्षलाई समर्थन गर्न, सेवा मानकहरू कायम गर्न, र पर्यटन प्राधिकरणहरूसँग सहकार्य गर्न उद्योगको समग्र विकासलाई बढाउन प्रतिबद्ध छौं।",
      previewTitle: "एकताको बारेमा",
      previewDescription: "एकता होटल तथा गेष्टहाउस व्यवसाय संघ नेपाल काठमाडौंको आतिथ्य क्षेत्रको प्रतिनिधित्व गर्ने एक समर्पित संस्था हो। २०७४ बि.स. मा स्थापित, एकताले {{count}} सक्रिय होटेल व्यवसाय संघहरूको छाता संगठनको रूपमा काम गर्दछ।",
      readFullStory: "पूरा कथा पढ्नुहोस्",
      leadershipTitle: "हाम्रो नेतृत्व",
      presidentTitle: "अध्यक्ष, एकता काठमाडौं",
    },
    hotels: {
      title: "होटेल निर्देशिका",
      subtitle: "काठमाडौंमा प्रिमियम होटलहरू पत्ता लगाउनुहोस्",
      search: "होटलहरू खोज्नुहोस्...",
      filter: "फिल्टर",
      sortBy: "क्रमबद्ध गर्नुहोस्",
      location: "स्थान",
      rating: "मूल्याङ्कन",
      priceRange: "मूल्य दायरा",
      amenities: "सुविधाहरू",
      viewDetails: "विवरण हेर्नुहोस्",
      bookNow: "अहिले बुक गर्नुहोस्",
      perNight: "प्रति रात",
      reviews: "समीक्षाहरू",
      noResults: "कुनै होटल फेला परेन",
    },
    destinations: {
      title: "गन्तव्यहरु",
      subtitle: "काठमाडौंका प्रतिष्ठित स्थलहरू अन्वेषण गर्नुहोस्",
      viewAll: "सबै गन्तव्यहरू हेर्नुहोस्",
      explore: "अन्वेषण गर्नुहोस्",
      description: "विवरण",
      location: "स्थान",
      openingHours: "खुल्ने समय",
      entryFee: "प्रवेश शुल्क",
    },
    events: {
      title: "कार्यक्रमहरु",
      subtitle: "आगामी कार्यक्रमहरू र गतिविधिहरू",
      upcoming: "आगामी कार्यक्रमहरू",
      past: "विगतका कार्यक्रमहरू",
      date: "मिति",
      time: "समय",
      venue: "स्थान",
      register: "अहिले दर्ता गर्नुहोस्",
      details: "कार्यक्रम विवरण",
      noEvents: "कुनै कार्यक्रम तालिकाबद्ध छैन",
    },
    gallery: {
      title: "फोटो ग्यालेरी",
      subtitle: "हाम्रो छविहरूको संग्रह अन्वेषण गर्नुहोस्",
      viewImage: "छवि हेर्नुहोस्",
      download: "डाउनलोड गर्नुहोस्",
      share: "साझा गर्नुहोस्",
    },
    contact: {
      title: "हामीलाई सम्पर्क गर्नुहोस्",
      subtitle: "हामीसँग सम्पर्कमा रहनुहोस्",
      name: "नाम",
      email: "इमेल",
      phone: "फोन",
      message: "सन्देश",
      send: "सन्देश पठाउनुहोस्",
      sending: "पठाउँदै...",
      success: "सन्देश सफलतापूर्वक पठाइयो!",
      error: "सन्देश पठाउन असफल भयो। कृपया पुन: प्रयास गर्नुहोस्।",
      address: "ठेगाना",
      officeHours: "कार्यालय समय",
      followUs: "हामीलाई फलो गर्नुहोस्",
    },
    auth: {
      login: "लगइन",
      signup: "साइन अप",
      logout: "लगआउट",
      email: "इमेल ठेगाना",
      password: "पासवर्ड",
      confirmPassword: "पासवर्ड पुष्टि गर्नुहोस्",
      forgotPassword: "पासवर्ड बिर्सनुभयो?",
      rememberMe: "मलाई सम्झनुहोस्",
      noAccount: "खाता छैन?",
      haveAccount: "पहिले नै खाता छ?",
      resetPassword: "पासवर्ड रिसेट गर्नुहोस्",
      backToLogin: "लगइनमा फर्कनुहोस्",
    },
    footer: {
      brand: "एकता होटल तथा गेस्टहाउस व्यवसायी सङ्घ, नेपालको राजधानीमा प्रीमियम आतिथ्य र उत्कृष्टता प्रतिनिधित्व गर्दै।",
      quickLinks: "द्रुत लिङ्कहरु",
      resources: "संसाधनहरु",
      contact: "संपर्क",
      phone: "फोन",
      email: "इमेल",
      location: "स्थान",
      officeHours: "कार्यालय समय: 9AM - 5PM (आइतबार - शुक्रबार)",
      rights: "सर्वाधिकार सुरक्षित",
      socialLabel: "सामाजिक लिङ्कहरु",
      privacyPolicy: "गोपनीयता नीति",
      termsOfService: "सेवा सर्तहरू",
    },
    members: {
      title: "सदस्यहरु",
      balaju: "बलाजु होटेल व्यवसाय संघ",
      kalanki: "कलंकी होटेल र अतिथि गृह संघ",
      kathmandu: "काठमाडौं होटेल व्यवसाय संघ",
      nepalguesthouse: "नेपाल अतिथि गृह व्यवसाय संघ",
      sundhara: "सुन्धरा होटेल व्यवसाय संघ",
      united: "संयुक्त होटेल र अतिथि गृह",
      nepalihotel: "नेपाली होटेल व्यवसाय संघ",
      relatedOrgs: "सम्बन्धित संस्थाहरु",
      membersCount: "सदस्यहरु",
      viewProfile: "प्रोफाइल हेर्नुहोस्",
      contactMember: "सदस्यलाई सम्पर्क गर्नुहोस्",
    },
    common: {
      learnMore: "अझ जान्नुहोस्",
      viewAll: "सबै देख्नुहोस्",
      position: "पद",
      phone: "फोन",
      contact: "संपर्क",
      loading: "लोड हुँदैछ...",
      error: "त्रुटि",
      success: "सफलता",
      cancel: "रद्द गर्नुहोस्",
      save: "सुरक्षित गर्नुहोस्",
      edit: "सम्पादन गर्नुहोस्",
      delete: "मेटाउनुहोस्",
      confirm: "पुष्टि गर्नुहोस्",
      back: "पछाडि",
      next: "अर्को",
      previous: "अघिल्लो",
      search: "खोज्नुहोस्",
      filter: "फिल्टर",
      sort: "क्रमबद्ध",
      close: "बन्द गर्नुहोस्",
    },
  },
}
